//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DAL.ExpenseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deposit
    {
        public int Id { get; set; }
        public System.DateTime CreditDate { get; set; }
        public string Amount { get; set; }
        public Nullable<int> PaymentMethodId { get; set; }
        public string CreditedBy { get; set; }
        public string CreditedTo { get; set; }
        public string Description { get; set; }
        public string CarryForwardAmount { get; set; }
        public string CreatedBy { get; set; }
        public System.DateTime CreatedAt { get; set; }
        public string UpdatedBy { get; set; }
        public System.DateTime UpdatedAt { get; set; }
    
        public virtual LookUpDetail LookUpDetail { get; set; }
    }
}
